### PR TITLE
Add codemp wheel to dependencies

### PR DESCRIPTION
**Pull request by ghyatzo**
I am developing a plugin that needs this library, and would love to be able to just have it ready without needing to ship it with the plugin itself.

### CODE REVIEW

**Comment by deathaxe** [comment]
Importing codemp fails on Windows.

```
>>> import codemp
Traceback (most recent call last):
  File "__main__", line 1, in <module>
  File "C:\Apps\Sublime Text 40xx\Data\Lib\python38\codemp\__init__.py", line 1, in <module>
    from .codemp import *
ImportError: DLL load failed while importing codemp: Das angegebene Modul wurde nicht gefunden.
```

**Comment by ghyatzo** [comment]
Thank you, I'll see what I can do.

**Comment by deathaxe** [comment]
It may also be a design fault on libraries or rust build tool chain.

I've seen such issues only with packages shipping compiled rust libraries so far.

**Comment by ghyatzo** [comment]
I've been investigating it and there is some windows specific cross compilation shenanigans regarding python.dll. But I'd need to test it. I thought I was out of the weeds by seeing it in the normal python 38 interpreter.

**Comment by ghyatzo** [comment]
This could be an issue of the wheel being built with `abi3` support (https://peps.python.org/pep-0384/#linkage).
Where on windows it is expected to have a `python3.dll` while on unix-likes this dependency is managed directly by the interpreter itself.

I'll need to test this with a full `cp38-cp38-win_amd64` wheel instead

**Comment by ghyatzo** [comment]
Hi @deathaxe, I've changed the wheel for windows, and now is a version without abi. I've tested on a windows machine I had laying around, and it seems to work now, can you test again on yours please? :)

**Pull request merged**
